# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8100 # Ensure this matches the containerPort and app port
